include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    empty_catches: true
